### ISSUE TITLE
string.matches not populating errors correctly

### ISSUE THREAD

**Issue by jasonblanchard** [jquense/yup#121]
I'm pretty sure [something in this code](https://github.com/jquense/yup/blob/master/src/string.js#L88) isn't populating the validation errors correctly for [`string.matches`](https://github.com/jquense/yup#stringmatchesregex-regex-message-string-schema). Here's a failing test:

```js
  it('MATCHES should populate the error message', async () => {
    let v = string().matches(/(hi|bye)/);

    let error = await v.validate('cats').should.be.rejected();

    expect(error.message).to.match(/must match the following/);
  });
```

```
 FAIL  test/string.js
  ● String types › MATCHES should populate the error message

    AssertionError: expected {} to match /must match the following/

      at _callee$ (test/string.js:130:38)
      at tryCatch (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/string.js:3:470)
      at test/string.js:3:630
```

It's returning an empty object, which is indeed what we're seeing in our codebase when we use `matches` without passing in a `message` argument. It works as expected if we give it a `message` argument).

The default error message should _never_ be an empty object, right? Maybe I'm missing something....

**Comment by jasonblanchard** [comment]
Updated original description. The test was written wrong, but it's still failing in the same way.

**Comment by jasonblanchard** [comment]
For comparison, here's the same test with `string.max` which is passing:

```js
  it('MATCHES should populate the error message', async () => {
    // let v = string().matches(/(hi|bye)/);
    let v = string().max(1);

    let error = await v.validate('cats').should.be.rejected();

    // expect(error.message).to.match(/must match the following/);
    expect(error.message).to.match(/must be at most/);
  });
```

I would expect `string.matches` to behave the same way.

**Comment by jasonblanchard** [comment]
I think [this line](https://github.com/jquense/yup/blob/73c44d798c7adf438b249703fdeba1490e696c33/src/string.js#L92) is causing it.

Since the `options` argument defaults to `{}`, when `options.message` isn't passed in AND `options` does not have `excludeEmptyString`, `message` is ALWAYS going to be set to `{}` and `locale.matches` will NEVER be used.

What's the purpose of that line? Can we remove it?

**Comment by jasonblanchard** [comment]
Oh, I guess that's required to use the `string.matches(/something/, 'some message')` signature... maybe don't default `options` to `{}`?

**Comment by sebpiq** [comment]
yeah, got the same error here. Happy to submit a PR as well, but not sure what should be the desired behavior

**Comment by jquense** [comment]
the switch is to allow the overload of providing a string message or an options object. We want to keep the current api just fix the bug :)

**Comment by sebpiq** [comment]
so something like

```
    if (typeof options === 'string')
      message = options;
    else if (options)
      ({ excludeEmptyString, message } = options) 
```

**Comment by ctavan** [comment]
FYI this issue is fixed in the `jupp`-fork and [released with v0.27.0 of it](https://github.com/ctavan/jupp/releases/tag/v0.27.0). See https://github.com/ctavan/jupp/pull/7

**Comment by chasecaleb** [comment]
The bug is still present due to the default `options = {}` parameter. Permalink of the offending line in what is currently master, as pointed out by @jasonblanchard from last year: https://github.com/jquense/yup/blob/dd50c4e34299c08ea0c43ba1685c314b11dc4ee5/src/string.js#L74

@jquense I'm not sure if you meant to close this issue or not, are you aware that it's still broken? If you don't have time to fix it, would you accept a PR from me or @jasonblanchard ?
