### ISSUE TITLE
Accessing the "final" schema and extracting it's rules

### ISSUE THREAD

**Issue by alexandernst** [jquense/yup#1280]
Let's say I have the following schema (one of the examples in Yup's documentation):

```
let schema = object({
  isSpecial: boolean(),
  isBig: boolean(),
  count: number().when(['isBig', 'isSpecial'], {
    is: true, // alternatively: (isBig, isSpecial) => isBig && isSpecial
    then: yup.number().min(5),
    otherwise: yup.number().min(0),
  }),
});

const result = schema.validateSync({
  isBig: true,
  isSpecial: true,
  count: 10,
});
```

The `count` min value depends on the value of `isBig`. That value is decided at runtime, when calling `validate()`.
Is there a way I can somehow access the "final" schema and programatically check what Yup decided to enforce?

Something like:

```
const { result, finalSchema } = schema.validateSync({
  isBig: true,
  isSpecial: true,
  count: 10,
});

console.log(finalSchema.count.min) // 5
```

**Comment by jquense** [comment]
you can use `schema.resolve({ value: yourValue })`

**Comment by alexandernst** [comment]
@jquense That method is not documented. Furthermore, how can I access the rules / conditions that Yup resolved?

I see that I can access the fields with `resolvedSchema.fields.foo`, but then how can I check what was the actual `min` value that Yup choose to set? I don't see any methods in the docs that would allow me to "read" the defined rules of a schema.

**Comment by jquense** [comment]
> That method is not documented

that is correct

>  how can I access the rules / conditions that Yup resolved?

`schema.describe()` will output metadata about the current schema.

**Comment by alexandernst** [comment]
I saw the `.describe()` method, but the data that it returns doesn't contain what I'm looking for.
I'm guessing that the values that I'm interested in should be inside the `tests[]` array from the data returned by `describe()`, but that array is always empty, no matter which field of my schema I try to describe.

I tried describing the schema itself and then inspecting the fields manually, but still the same result.

![Devilline_Diagramer](https://user-images.githubusercontent.com/89727/109048581-879a1380-76d7-11eb-8301-9a80f0f1c24f.png)

**Comment by jquense** [comment]
if it's empty it usually means it resolved to no tests, but certainly could be a bug. If you want to put a codesandbox that demonstrates the issue i can look

**Comment by alexandernst** [comment]
Sure thing! I need ~10min

**Comment by alexandernst** [comment]
Done @jquense : https://codesandbox.io/s/lucid-breeze-8e7st?file=/src/index.js

**Comment by jquense** [comment]
ah, I see, right this is because with `resolved` doesn't resolve "deeply". Hmm i'm not sure how you might deal with this, there should probably a way to do this

**Comment by alexandernst** [comment]
@jquense Do you use bug bounty? I'm really interested in this feature!

**Comment by jakobsandberg** [comment]
@alexandernst as mentioned above, `schema.resolve()` won't resolve nested schemas. We must instead resolve the nested schema, `count` in this case, via `yup.reach()`.

Now that we're resolving at the nested schema, we'll need to provide a `parent` object to `schema.resolve()` in order for this nested schema to access the values of its siblings.

```
const resolved = yup.reach(schema, 'count').resolve({
    parent: {
        isBig: true,
        isSpecial: true,
        count: 10
    }
});
```

**Comment by alexandernst** [comment]
@jakobsandberg Manually resolving "count" works as long as the schema is kept "simple".

I tried something a little bit more advanced and Yup isn't capable of resolving the tests correctly. 

Demo: https://codesandbox.io/s/charming-dew-w07or?file=/src/index.js:0-818

Example code (just in case the link dies)

```
import { reach, object, array, number, string } from "yup";

let schema = object({
  type: array()
    .of(string().oneOf(["standard", "advanced"]))
    .default(["standard"]),
  size: number()
    .required()
    .when("type", (type, schema) => {
      const [t] = type || [];
      switch (t) {
        case "standard":
          return schema.min(1).max(100).default(10);
        case "advanced":
          return schema.min(101).max(200).default(150);
        default:
          return schema.default(10);
      }
    })
});

const resolved = reach(schema, "size").resolve({
  parent: {
    type: "standard",
    size: 10
  }
});

const described = resolved.describe();

console.log(described);

// described.tests should contain the "required", "min" and "max" tests,
// but it contains only the "required" test.
```

**Comment by alexandernst** [comment]
Sorry, my bad. The `type`'s value should be `["standard"]`. I need to further test this.

**Comment by alexandernst** [comment]
@jakobsandberg I can confirm that your workaround works fine. It would be nice if Yup could resolve nested schemas by default though.

**Comment by jakobsandberg** [comment]
> It would be nice if Yup could resolve nested schemas by default though.

Yes, that would be handy. Fortunately, Yup provides a good API for extending functionality like this.

For example, you can add a `resolveDeep` method to your schemas that traverses the schema and resolves each node in a similar manner to the workaround I posted above.

```javascript
yup.addMethod(yup.mixed, 'resolveDeep', function(values) {
  // traverse schema and resolve each node 
})
```
