### ISSUE TITLE
optional properties

### ISSUE THREAD

**Issue by fourq** [jquense/yup#3]
I'd like to be able to set a property as optional. What do you think about this?

**Comment by jquense** [comment]
Properties should be are optional by default, and by optional I mean "not `required()`". Are you thinking that there should be some sort of different behavior? I might need a demonstration of what you are looking for

**Comment by fourq** [comment]
I mean, if my schema is

let schema = {
    name: Yup.string(),
    id: Yup.string
};

If I validate an obj that doesn't have the `name` prop it fails. I've been setting everything to nullable and including the null property to pass tests.

Am I thinking about this incorrectly?

**Comment by jquense** [comment]
It shouldn't fail, "presence" is determined by `undefined`. `null` is considered a separate type generally, because the sematics of it are weird (for instance: does a null object mean not there, or invalid object?). If you want `null` to be considered a valid value for a type that's where nullable comes in. You can check it out here: http://requirebin.com/?gist=a02641b4ab651ce7a7db

```js
var yup = require('yup')
var assert = require('assert')

var schema = yup.object({
  name: yup.string(),
  id: yup.string()
});

// works with implicit or explicit undefined
schema.isValid({ id: undefined }).then(function(valid){
  assert(valid)
  console.log('fin')
})
```

**Comment by fourq** [comment]
I mean, if the object i'm validating doesn't have the property at all. (I removed the `city` prop)

Schema: https://gist.github.com/13961916b067a9cfd291
Test: https://gist.github.com/2f440aa2df4bdb5d5be3
Error: 
```
err: { [ValidationError: Invalid City]
  name: 'ValidationError',
  errors: [ 'Invalid City' ],
  message: 'Invalid City' }
```

**Comment by fourq** [comment]
It might be because there's a condition on yup.string().max(100)

**Comment by jquense** [comment]
> It might be because there's a condition on yup.string().max(100)

Probably that, the fix to your other issue, should address this.

**Comment by jquense** [comment]
fixed with: https://github.com/jquense/yup/commit/22ea6d1d79cd989f068d6bb7c07a0d0c397b69a1

**Comment by fourq** [comment]
wow! super fast. I'll try it out now. TY!

**Comment by ruscoder** [comment]
Problem not fixed for string values. Check #16 issue
For string value always not null. Empty values always is '' - empty string
